apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: zg8z1pgu3-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-3b215fdfdc.dcpy.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:40502998c9c34a609bc499e3f74d34c26904eb13@sha256:dd88087e4663b017a877732c29d74d006f55ee6a9e7fd060e1eb387c59838984
        name: container-image  
