apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zg8z1pgu3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/zg8z1pgu3-java-quarkus-gitops